{{- if and (.Values.invenio.sentry.enabled) (and (not .Values.invenio.sentry.existingSecret) (not .Values.invenio.sentry.existing_secret)) }}
{{- $dsn := .Values.invenio.sentry.dsn | required ".Values.invenio.sentry.dns is required unless existingSecret is provided." -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sentry-secrets
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
    app: sentry-secrets
  annotations:
    helm.sh/resource-policy: keep
data:
  {{ .Values.invenio.sentry.secretKeys.dsnKey }}: {{ $dsn | b64enc }}
{{- end -}}
