{{- with .Values.invenio.vocabularies }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: invenio-vocabularies
  labels:
    {{- include "invenio.labels" $ | nindent 4 }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
